### ISSUE TITLE
Test new issue parsing

### ISSUE THREAD

**Issue by cladmi** [cladmi/Release-Specs#1]
This issue lists the status of all tests for the [Release Candidate 2 of the 2018.07](https://github.com/RIOT-OS/RIOT/releases/tag/2018.07-RC2) release.

Specs tested:
- [ ] [01-ci](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/01-ci/01-ci.md)
  - [ ] [Task #01 - Compile test](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/01-ci/01-ci.md#task-01---compile-test)
  - [ ] [Task #02 - Unittests on native](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/01-ci/01-ci.md#task-02---unittests-on-native)
  - [ ] [Task #03 - Unittests on native separated](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/01-ci/01-ci.md#task-03---unittests-on-native-separated)
  - [ ] [Task #04 - Unittests on iotlab-m3](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/01-ci/01-ci.md#task-04---unittests-on-iotlab-m3)
- [ ] [02-tests](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/02-tests/02-tests.md)
  - [ ] [Task #01 - All tests on native](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/02-tests/02-tests.md#task-01---all-tests-on-native)
  - [ ] [Task #02 - Subset of tests on iotlab-m3](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/02-tests/02-tests.md#task-02---subset-of-tests-on-iotlab-m3)
  - [ ] [Task #03 - Subset of tests on samr21-xpro](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/02-tests/02-tests.md#task-03---subset-of-tests-on-samr21-xpro)
- [ ] [03-single-hop-ipv6-icmp](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md)
  - [ ] [Task #01 - ICMPv6 multicast echo on native](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-01---icmpv6-multicast-echo-on-native)
  - [ ] [Task #02 - ICMPv6 link-local echo on native](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-02---icmpv6-link-local-echo-on-native)
  - [ ] [Task #03 - ICMPv6 link-local echo on native (1 hour)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/03-single-hop-ipv6-icmp/03-single-hop-ipv6-icmp.md#task-03---icmpv6-link-local-echo-on-native-1-hour)
- [ ] [04-single-hop-6lowpan-icmp](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md)
  - [ ] [Task #01 - ICMPv6 link-local echo with iotlab-m3](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-01---icmpv6-link-local-echo-with-iotlab-m3)
  - [ ] [Task #02 - ICMPv6 multicast echo with iotlab-m3/samr21-xpro](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-02---icmpv6-multicast-echo-with-iotlab-m3samr21-xpro)
  - [ ] [Task #03 - ICMPv6 echo with large payload](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-03---icmpv6-echo-with-large-payload)
  - [ ] [Task #04 - ICMPv6 echo with iotlab-m3/samr21-xpro 15 minutes](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-04---icmpv6-echo-with-iotlab-m3samr21-xpro-15-minutes)
  - [ ] [Task #05 (Experimental) - ICMPv6 multicast echo with samr21-xpro/remote](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-05-experimental---icmpv6-multicast-echo-with-samr21-xproremote)
  - [ ] [Task #06 (Experimental) - ICMPv6 link-local echo with samr21-xpro/remote](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-06-experimental---icmpv6-link-local-echo-with-samr21-xproremote)
  - [ ] [Task #07 (Experimental) - ICMPv6 multicast echo with samr21-xpro/zero + xbee](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-07-experimental---icmpv6-multicast-echo-with-samr21-xprozero--xbee)
  - [ ] [Task #08 (Experimental) - ICMPv6 echo with samr21-xpro/zero + xbee 15 minutes](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/04-single-hop-6lowpan-icmp/04-single-hop-6lowpan-icmp.md#task-08-experimental---icmpv6-echo-with-samr21-xprozero--xbee-15-minutes)
- [ ] [05-single-hop-route](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/05-single-hop-route/05-single-hop-route.md)
  - [ ] [Task #01 - ICMPv6 echo unicast addresess on native (default route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/05-single-hop-route/05-single-hop-route.md#task-01---icmpv6-echo-unicast-addresess-on-native-default-route)
  - [ ] [Task #02 - ICMPv6 echo unicast addresess on iotlab-m3 (default route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/05-single-hop-route/05-single-hop-route.md#task-02---icmpv6-echo-unicast-addresess-on-iotlab-m3-default-route)
  - [ ] [Task #03 - ICMPv6 echo unicast addresess on native (specific route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/05-single-hop-route/05-single-hop-route.md#task-03---icmpv6-echo-unicast-addresess-on-native-specific-route)
  - [ ] [Task #04 - ICMPv6 echo unicast addresess on iotlab-m3 (static route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/05-single-hop-route/05-single-hop-route.md#task-04---icmpv6-echo-unicast-addresess-on-iotlab-m3-static-route)
- [ ] [06-single-hop-udp](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/06-single-hop-udp/06-single-hop-udp.md)
  - [ ] [Task #01 - UDP on iotlab-m3](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/06-single-hop-udp/06-single-hop-udp.md#task-01---udp-on-iotlab-m3)
  - [ ] [Task #02 - UDP on iotlab-m3 (other port)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/06-single-hop-udp/06-single-hop-udp.md#task-02---udp-on-iotlab-m3-other-port)
- [ ] [07-multi-hop](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/07-multi-hop/07-multi-hop.md)
  - [ ] [Task #01 - ICMPv6 echo on iotlab-m3 with three hops (static route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/07-multi-hop/07-multi-hop.md#task-01---icmpv6-echo-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #02 - UDP on iotlab-m3 with three hops (static route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/07-multi-hop/07-multi-hop.md#task-02---udp-on-iotlab-m3-with-three-hops-static-route)
  - [ ] [Task #03 - ICMPv6 echo on iotlab-m3 with three hops (RPL route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/07-multi-hop/07-multi-hop.md#task-03---icmpv6-echo-on-iotlab-m3-with-three-hops-rpl-route)
  - [ ] [Task #04 - UDP on iotlab-m3 with three hops (RPL route)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/07-multi-hop/07-multi-hop.md#task-04---udp-on-iotlab-m3-with-three-hops-rpl-route)
- [ ] [08-interop](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md)
  - [ ] [Task #01 - ICMPv6 echo between native and Linux](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-01---icmpv6-echo-between-native-and-linux)
  - [ ] [Task #02 - ICMPv6 echo between iotlab-m3 and Linux with 6LowPAN](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-02---icmpv6-echo-between-iotlab-m3-and-linux-with-6lowpan)
  - [ ] [Task #03 - ICMPv6 echo between iotlab-m3 and Contiki](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-03---icmpv6-echo-between-iotlab-m3-and-contiki)
  - [ ] [Task #04 - ICMPv6 echo between iotlab-m3 and Internet host through Linux with 6LowPAN](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-04---icmpv6-echo-between-iotlab-m3-and-internet-host-through-linux-with-6lowpan)
  - [ ] [Task #05 - ICMPv6 echo between iotlab-m3 and Internet host through RIOT border router](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-05---icmpv6-echo-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #06 - UDP between iotlab-m3 and Internet host through RIOT border router](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-06---udp-between-iotlab-m3-and-internet-host-through-riot-border-router)
  - [ ] [Task #07 - UDP between iotlab-m3 and Internet host through RIOT border router (200b payload)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-07---udp-between-iotlab-m3-and-internet-host-through-riot-border-router-200b-payload)
  - [ ] [Task #08 - UDP between GNRC and lwIP on iotlab-m3 (not working)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-08---udp-between-gnrc-and-lwip-on-iotlab-m3-not-working)
  - [ ] [Task #09 - UDP between GNRC and emb6 on iotlab-m3](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-09---udp-between-gnrc-and-emb6-on-iotlab-m3)
  - [ ] [Task #10 - UDP between lwIP and emb6 on iotlab-m3 (not working)](https://github.com/cladmi/Release-Specs/blob/7b1d7b1d1f6142a8a96dce7337aa390cbac3df6e/08-interop/08-interop.md#task-10---udp-between-lwip-and-emb6-on-iotlab-m3-not-working)

Testing the new PR https://github.com/RIOT-OS/RIOT-release-manager/pull/3

**Comment by cladmi** [comment]
Updated.

**Comment by cladmi** [comment]
PR has been merged in the main repository.
